name: Playwright Tests

trigger:
  - main
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: one
    value: initialValue

jobs:
  - job: test
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - script: |
          printenv
        displayName: "list Env"

      - script: |
          npm install
        displayName: "Install dependencies"

      - script: |
          npx playwright install --with-deps
        displayName: "Install Playwright Browsers"

      - script: |
          npm run test
        displayName: "Run Playwright tests"

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "**/results.xml"
        condition: always()
