name: Playwright Tests

trigger:
  - main
  - master

jobs:
  - job: test
    timeoutInMinutes: 60
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo $(System.DefaultWorkingDirectory)
            pwd
            ls -l
            echo Change dir
            cd tests
            ls -l
