name: Playwright Tests

trigger: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: test
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install dependencies"
        workingDirectory: playwright/

      - script: |
          npx playwright install --with-deps
        displayName: "Install Playwright Browsers"
        workingDirectory: playwright/

      - script: |
          npm run test
        displayName: "Run Playwright tests"
        workingDirectory: playwright/

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "**/results.xml"
        condition: always()
